#!/bin/bash

set -ex 

if [ -f /app/src/Godeps ]; then
  TDIR=$(jq -r '.ImportPath' < /app/src/Godeps)
elif [ -f /app/src/Godeps/Godeps.json ]; then  
  TDIR=$(jq -r '.ImportPath' < /app/src/Godeps/Godeps.json)
elif [ -f /app/src/.godir ]; then
  TDIR=$(cat /app/go/t/.godir)
fi

mkdir -p /app/go/src/$(dirname $TDIR) && \
  ln -s /app/src /app/go/src/$TDIR && \
  cd /app/go/src/$TDIR && \
  godep go install ./...
