#!/bin/bash

set -ex 

if [ -f /app/src/Godeps ]; then
  GOVER=$(jq -r '.GoVersion' < /app/src/Godeps)
elif [ -f /app/src/Godeps/Godeps.json ]; then  
  GOVER=$(jq -r '.GoVersion' < /app/src/Godeps/Godeps.json)
fi

if [ -z "$GOVER" ]; then
  GOVER="go1.4.2"
fi

wget https://storage.googleapis.com/golang/${GOVER}.linux-amd64.tar.gz -q -O - | tar -zxf - -C /usr/local

GOPATH=/usr/local go get github.com/tools/godep/...
rm -rf /usr/local/src /usr/local/pkg
